export const POSTGRES_URL = "POSTGRES_URL";
export const PORT = "PORT";
export const PGHOST = "PGHOST";
export const PGDATABASE = "PGDATABASE";
export const PGUSER = "PGUSER";
export const PGPASSWORD = "PGPASSWORD";
export const FRONTEND_URL = "FRONTEND_URL";
export const DATABASE_URL = "DATABASE_URL";
export const DATABASE_URL_UNPOOLED = "DATABASE_URL_UNPOOLED";

export const JWT_SECRET = "JWT_SECRET";

export const ACCESS_TOKEN_VALIDITY_DURATION_IN_SEC = "ACCESS_TOKEN_VALIDITY_DURATION_IN_SEC";
